default:
  tags:
  - onpremise

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "test-CICD" 
      when: never
    - when: always
stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGEE
  USERNAME: $USERNAME
  HOST: $HOST
  PASSWORD_SERVER: $PASSWORD_SERVER
  DEV_ENDPOINT: https://auth.goavana.com
  

run_unit_tests:
  stage: test
  script:
    - echo "Running unit test"
  only:
    - test-CICD


build_image:
  stage: build
  before_script:
    - cd auth
    - export PVERSION=$(cat package.json | jq -r .version)
    - export VERSION=$PVERSION.$CI_PIPELINE_ID
    - echo $VERSION > version.txt
  script:
    - sshpass -p $PASSWORD_SERVER ssh -o StrictHostKeyChecking=no -l $USERNAME $HOST "
        cd /home/rahona/Microservice_Do_Ofisialy/CLOUD_SOURCES/stage-m2/auth &&
        git pull origin test-CICD &&
        docker build -t $IMAGE_NAME:$VERSION . "
  artifacts:
    paths:
      - auth/version.txt
  only:
    - test-CICD


push_image:
  stage: build
  needs:
    - build_image
  before_script:
    - cd auth
    - export VERSION=$(cat version.txt)
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORDD
  script:
    - docker tag $IMAGE_NAME:$VERSION auth:latest
    - docker push "$IMAGE_NAME:$VERSION"
    - docker logout
  only:
    - test-CICD

deploy_to_dev:
  stage: deploy
  script:
    - sshpass -p $PASSWORD_SERVER ssh -o StrictHostKeyChecking=no -l $USERNAME $HOST "
        cd /home/rahona/Microservice_Do_Ofisialy/Traefik_Microservice &&
        docker-compose down || true &&
        docker-compose up -d "
  only:
    - test-CICD
  environment:
    name: development
    url: $DEV_ENDPOINT
