default:
  tags:
  - onpremise

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "production" 
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGEE
  USERNAME: $USERNAME
  HOST: $HOST
  PASSWORD_SERVER: $PASSWORD_SERVER
  PROD_ENDPOINT: https://presence.goavana.com

  

run_unit_tests:
  stage: test
  script:
    - echo "Running unit test"
  only:
    - production



build_image:
  stage: build
  before_script:
    - export PVERSION=$(cat package.json | jq -r .version)
    - export VERSION=$PVERSION.$CI_PIPELINE_ID
    - echo $VERSION > version.txt
  script:
    - docker build -t $IMAGE_NAME:$VERSION .
  artifacts:
    paths:
      - version.txt
  only:
    - production


push_image:
  stage: build
  needs:
    - build_image
  before_script:
    - export VERSION=$(cat version.txt)
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORDD
  script:
    - docker tag $IMAGE_NAME:$VERSION todo_back_do-app-presence-tallymanager:latest
    - docker push $IMAGE_NAME:$VERSION
  only:
    - production

deploy_to_prod:
  stage: deploy
  before_script:
    - export VERSION=$(cat version.txt)
  script:
    - sshpass -p $PASSWORD_SERVER ssh -o StrictHostKeyChecking=no -l $USERNAME $HOST "
        cd /home/rahona/Microservice_Do_Ofisialy/Traefik_Microservice &&
        docker-compose down || true &&
        docker-compose up -d "
  only:
    - production
  environment:
    name: production
    url: $PROD_ENDPOINT
