default:
  tags:
  - onpremise

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "tracking" 
# && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGEE_TRACKING
  USERNAME: $USERNAME
  HOST: $HOST
  PASSWORD_SERVER: $PASSWORD_SERVER
  PROD_ENDPOINT: https://tracking.goavana.com
#  PROD_ENDPOINT: https://www.akata-goavana.com
  

run_unit_tests:
  stage: test
  script:
    - echo "Running unit test"
  only:
    - tracking



build_image:
  stage: build
  before_script:
    - export PVERSION=$(cat package.json | jq -r .version)
    - export VERSION=$PVERSION.$CI_PIPELINE_ID
    - echo $VERSION > version.txt
  script:
    - docker build -t $IMAGE_NAME:$VERSION .
  artifacts:
    paths:
      - version.txt
  only:
    - tracking


push_image:
  stage: build
  needs:
    - build_image
  before_script:
    - export VERSION=$(cat version.txt)
    - docker login -u $CI_REGISTRY_USERNAME_TRACKING -p $CI_REGISTRY_PASSWORD_TRACKING
  script:
    - docker tag $IMAGE_NAME:$VERSION tracking:latest
    - docker push $IMAGE_NAME:$VERSION
  only:
    - tracking

deploy_to_dev:
  stage: deploy
  before_script:
    - export VERSION=$(cat version.txt)
  script:
    - sshpass -p $PASSWORD_SERVER ssh -o StrictHostKeyChecking=no -l $USERNAME $HOST "
        cd /home/rahona/Microservice_Do_Ofisialy/Traefik_Microservice &&
        docker-compose down || true &&
        docker-compose up -d "
  only:
    - tracking
  environment:
    name: production
    url: $PROD_ENDPOINT

